/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import goblinHead from '../../assets/meshes/gobbohead.gltf'

export default function Goblin(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(goblinHead);
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 3.02, 0.31]}>
        <primitive object={nodes.root} />
        <skinnedMesh
          geometry={nodes.Cube.geometry}
          material={materials["Material.001"]}
          skeleton={nodes.Cube.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload(goblinHead);
