/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import noticeBoard from '../../assets/meshes/noticeBoard.gltf'

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(noticeBoard);
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.board.geometry}
        material={nodes.board.material}
        scale={[2.07, 1.44, -0.07]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        position={[0, 1.9, 0.09]}
        scale={[1.83, 0.49, 0.14]}
      />
    </group>
  );
}

useGLTF.preload(noticeBoard);