/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import roomModel from '../../assets/meshes/room.gltf'

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(roomModel);
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        position={[-3, 1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.96, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={nodes.Plane001.material}
        position={[0, 1, 2]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[2, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={nodes.Plane002.material}
        position={[-2, 0, 2]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[2, 1, 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.window_frame.geometry}
        material={nodes.window_frame.material}
        position={[-2.0058, 1.6072, 0.0137]}
        scale={[0.0563, 0.0258, 0.0314]}
      />
    </group>
  );
}

useGLTF.preload(roomModel);
